# Generated by Django 4.2.5 on 2023-10-05 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_productcolor_remove_product_colour_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImages",
        ),
    ]
